services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: backend
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - .env
    image: backend:latest 
    networks:
      - fileflow-network
  db:
    image: postgres:15
    container_name: db
    restart: always
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - fileflow-network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    env_file:
      - .env
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    networks:
      - fileflow-network

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      app:
        condition: service_started
      db:
        condition: service_healthy
    volumes:
      - .:/app
      - ./reports:/app/reports
    working_dir: /app
    ports:
      - "8080:8080"
    command: >
      bash -c "
       set -e
       set -x
       alembic upgrade head
       uv add coverage 
       coverage run --source=app -m pytest
       coverage report --show-missing
       coverage html --title \"$${1:-Test Coverage}\"
       "
    profiles:
      - app_test
    networks:
      - fileflow-network

networks:
  fileflow-network:
    driver: bridge


volumes:
  postgres_data:
  mongo_data: