FROM ghcr.io/astral-sh/uv:python3.12-bookworm-slim

WORKDIR /app

COPY --from=ghcr.io/astral-sh/uv:0.5.11 /uv /uvx /bin/

RUN useradd -m -s /bin/bash appuser

# Copy dependency files
COPY ./pyproject.toml ./uv.lock ./alembic.ini ./.python-version /app/

RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --frozen --no-dev

# Ref: https://docs.astral.sh/uv/guides/integration/docker/#using-the-environment
ENV PATH="/app/.venv/bin:$PATH"

# Ref: https://docs.astral.sh/uv/guides/integration/docker/#compiling-bytecode
ENV UV_COMPILE_BYTECODE=1


# Ref: https://docs.astral.sh/uv/guides/integration/docker/#caching
ENV UV_LINK_MODE=copy

ENV PYTHONPATH=/app

COPY ./app /app/app
COPY ./alembic /app/alembic

RUN chown -R appuser:appuser /app

USER appuser

CMD ["bash", "-c", \
    "set -e && \
     echo 'Waiting for database to be ready...' && \
     sleep 5 && \
     echo 'Starting and Running Database Migrations...' && \
     uv run alembic upgrade head && \
     echo 'Starting FastAPI application...' && \
     exec fastapi run app/main.py --port 8080 --reload"]

# will add this later "--proxy-headers", when I add Traefik