FROM python:3.13-slim-bookworm

WORKDIR /code

COPY ./requirements.txt /code/requirements.txt

COPY ./requirements-dev.txt /code/requirements-dev.txt

RUN pip install --no-cache-dir -r requirements.txt -r requirements-dev.txt

COPY ./app /code/app

CMD ["bash", "-c", \
     "set -e && \
      echo 'Waiting for database to be ready...' && \
      sleep 5 && \
      echo 'Starting and Running Database Migrations...' && \
      alembic upgrade head && \
      echo 'Starting FastAPI application...' && \
      exec fastapi run app/main.py --port 8080 --reload"]

#will add this later "--proxy-headers", when I add Traefik