"""Added on_delete = 'CASCADE'

Revision ID: 06e7bdfc37d9
Revises: f3b8631f8e6c
Create Date: 2025-05-08 00:38:33.911443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06e7bdfc37d9'
down_revision: Union[str, None] = 'f3b8631f8e6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('usergrouplink_group_id_fkey', 'usergrouplink', type_='foreignkey')
    op.drop_constraint('usergrouplink_user_id_fkey', 'usergrouplink', type_='foreignkey')
    op.create_foreign_key(None, 'usergrouplink', 'group', ['group_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'usergrouplink', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usergrouplink', type_='foreignkey')
    op.drop_constraint(None, 'usergrouplink', type_='foreignkey')
    op.create_foreign_key('usergrouplink_user_id_fkey', 'usergrouplink', 'user', ['user_id'], ['id'])
    op.create_foreign_key('usergrouplink_group_id_fkey', 'usergrouplink', 'group', ['group_id'], ['id'])
    # ### end Alembic commands ###
