"""Added created_at field

Revision ID: a46f8f4b15ec
Revises: 06e7bdfc37d9
Create Date: 2025-05-08 18:23:25.577101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a46f8f4b15ec'
down_revision: Union[str, None] = '06e7bdfc37d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group', 'created_at')
    # ### end Alembic commands ###
