"""add type field to ExceptionLog

Revision ID: a965b2312d59
Revises: 02b2b5e0377a
Create Date: 2025-05-27 10:02:24.699140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a965b2312d59'
down_revision: Union[str, None] = '02b2b5e0377a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exceptionlog', sa.Column('error_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_exceptionlog_error_type'), 'exceptionlog', ['error_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exceptionlog_error_type'), table_name='exceptionlog')
    op.drop_column('exceptionlog', 'error_type')
    # ### end Alembic commands ###
