"""Update Group

Revision ID: b1e4f04551b6
Revises: 3a8b65ab6cc1
Create Date: 2025-05-04 18:52:24.600773

"""
from typing import Sequence, Union
import sqlmodel.sql.sqltypes
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1e4f04551b6'
down_revision: Union[str, None] = '3a8b65ab6cc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
    op.add_column('group', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.drop_constraint('group_name_key', 'group', type_='unique')
    op.drop_column('group', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.create_unique_constraint('group_name_key', 'group', ['name'])
    op.drop_column('group', 'description')
    op.drop_column('group', 'title')
    # ### end Alembic commands ###
