"""Update to current models

Revision ID: f3b8631f8e6c
Revises: b1e4f04551b6
Create Date: 2025-05-04 21:54:50.421374

"""
from typing import Sequence, Union
import sqlmodel.sql.sqltypes
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3b8631f8e6c'
down_revision: Union[str, None] = 'b1e4f04551b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usergrouplink', sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('usergrouplink', sa.Column('date_joined', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usergrouplink', 'date_joined')
    op.drop_column('usergrouplink', 'role')
    # ### end Alembic commands ###
